version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
        - KubesenseCore
        - KubesenseLogs
        - KubesenseTrace
        - KubesenseRUM
        - KubesenseSessionReplay
        - KubesenseCrashReporting
        - KubesenseWebViewTracking
        - KubesenseFlags
        - KubesenseProfiling
