## Workaround KSCrash static linking issue
# https://github.com/kstenerud/KSCrash/issues/713
use_modular_headers!
#

target 'Runner iOS' do
    platform :ios, '15.0'

    pod 'KubesenseCore', :path => '..'
    pod 'KubesenseLogs', :path => '..'
    pod 'KubesenseTrace', :path => '..'
    pod 'KubesenseRUM', :path => '..'
    pod 'KubesenseCrashReporting', :path => '..'
    pod 'KubesenseSessionReplay', :path => '..'
    pod 'KubesenseWebViewTracking', :path => '..'

    target 'IntegrationScenarios' do
        pod 'KubesenseInternal', :path => '..'
        pod 'TestUtilities', :path => '..'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) KUBESENSE_SDK_ENABLE_EXPERIMENTAL_APIS KUBESENSE_SDK_COMPILED_FOR_TESTING'
        end
    end
end
